Controllers/CitasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using CCVLab.Models;
using System.Security.Claims;
using CCVLab.Data;
using CCVLab.Services;

namespace CCVLab.Controllers
{
    public class CitasController : Controller
    {
        private readonly IService_API _serviceApi;
        private readonly IService_API_Paciente _serviceApiPaciente;
        private readonly IService_API_Examen _serviceApiExamen;

        public CitasController(IService_API service_API, IService_API_Paciente service_API_Paciente, IService_API_Examen service_API_Examen)
        {
            _serviceApi = service_API;
            _serviceApiPaciente = service_API_Paciente;
            _serviceApiExamen = service_API_Examen;
        }
        public async Task<ActionResult> ListarCitas()
        {
            List<ViewCita> lista = await _serviceApi.Lista();
            return View(lista);
        }
        public async Task<ActionResult> CrearCitas()
        {
            var listaPacientes = await _serviceApiPaciente.Lista();
            var listaExamenes = await _serviceApiExamen.Lista();

            ViewBag.ListaPacientes = listaPacientes;
            ViewBag.listaExamenes = listaExamenes;

            return View();
        }
        public async Task<ActionResult> Cita(int ID)
        {
            Cita modelo_cita = new Cita();

            ViewBag.Accion = "Nueva Cita";

            if (ID != 0)
            {
                modelo_cita = await _serviceApi.ObtenerCita(ID);
                ViewBag.Accion = "Editar Cita";
            }
            return View(modelo_cita);
        }

        public async Task<ActionResult> DetalleCitas(int ID)
        {
            Cita modelo_cita = new Cita();/*Se debe traer al modelo correspondiente*/

            ViewBag.Accion = "Nueva Cita";

            if (ID != 0)
            {
                modelo_cita = await _serviceApi.ObtenerCita(ID);
                ViewBag.Accion = "Detalle de la Cita";
            }
            return View(modelo_cita);
        }

        [HttpPost]
        public async Task<ActionResult> GuardarCita(CreateCitaModel obj_cita)
        {
            bool respuesta;

            if (obj_cita.ID == 0)
            {
                var examenesSeleccionadosValues = Request.Form["Examenes"];
                if (examenesSeleccionadosValues.Count > 0)
                {
                    obj_cita.Examenes = examenesSeleccionadosValues.Select(int.Parse).ToList();
                }

                respuesta = await _serviceApi.CreateCita(obj_cita);
            }
            else
            {
                respuesta = await _serviceApi.UpdateCita(obj_cita);
            }

            if (respuesta)
                return RedirectToAction("ListarCitas");
            else
                return NoContent();
        }
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using CCVLab.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using CCVLab.Data;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace CCVLab.Controllers
{
    public class LoginController : Controller
    {
        private readonly DatabaseContext _context;
        //private readonly DA_Login _dalogin;
        private readonly ILogger<HomeController> _logger;
        public LoginController(ILogger<HomeController> logger,
         DatabaseContext context)
        {
            _logger = logger;
            _context = context;
           // _dalogin = dalogin;
        }
        public IActionResult Login()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> Login(Usuario model)
        {
            if (ModelState.IsValid)
            {
                var usuario = await _context.Usuarios
            .Include(u => u.UsuarioRol)
            .ThenInclude(ur => ur.Rol)
            .FirstOrDefaultAsync(u => u.Email == model.Email && u.Password == model.Password);

                if (usuario != null)
                {
                    // Autenticación exitosa
                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, usuario.Nombres),
                        new Claim(ClaimTypes.Surname, usuario.Apellidos),
                        new Claim(ClaimTypes.NameIdentifier, usuario.ID.ToString()),
                        new Claim("Correo", usuario.Email)
                    };

                    foreach (var usuarioRol in usuario.UsuarioRol)
                    {
                        if(usuarioRol.Rol != null)
                        {
                            claims.Add(new Claim(ClaimTypes.Role, usuarioRol.Rol.Nombre));
                        }
                    }

                    var claimsIdentity = new ClaimsIdentity(claims,CookieAuthenticationDefaults.AuthenticationScheme);

                    var authProperties = new AuthenticationProperties
                    {
                        IsPersistent = true,
                    };

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);

                    return RedirectToAction("ListarCitas", "Citas");
                }

                ModelState.AddModelError(string.Empty, "Email o clave incorrectos.");
            }

            return View(model);
        }

        // GET: LoginController/Details/5
        public ActionResult Pruebas(int id)
        {
            return View();
        }

        // GET: LoginController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LoginController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LoginController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LoginController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LoginController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LoginController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/PacienteController.cs
using CCVLab.Models;
using CCVLab.Services;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CCVLab.Controllers
{
    public class PacienteController : Controller
    {
        private readonly IService_API_Paciente _serviceApi;

        public PacienteController(IService_API_Paciente service_API)
        {
            _serviceApi = service_API;

        }
        public async Task<ActionResult> ListarPacientes(string dni = "")
        {
            List<Paciente> lista = await _serviceApi.Lista();

            if (!string.IsNullOrEmpty(dni))
            {
                lista = lista.Where(p => p.Nro_DNI.Contains(dni)).ToList();
            }

            return View(lista);
        }
        public async Task<ActionResult> BuscarPaciente(string dni)
        {
            List<Paciente> lista = await _serviceApi.Lista();

            if (!string.IsNullOrEmpty(dni))
            {
                lista = lista.Where(p => p.Nro_DNI.Contains(dni)).ToList();
            }

            return View("ListarPacientes", lista);
        }
        public IActionResult Crearpaciente()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> CreatePaciente(Paciente obj_paciente)
        {
            bool respuesta;

            Console.WriteLine("El modelo fue tomado correctamente.");
            respuesta = await _serviceApi.CreatePaciente(obj_paciente);

            if (respuesta)
            {
                return RedirectToAction("ListarPacientes");
            }
            else
            {
                return NoContent();
            }
        }
        public async Task<ActionResult> Form_Paciente(int ID)
        {
            Paciente modelo_paciente = new Paciente();/*Se debe traer al modelo correspondiente*/

            ViewBag.Accion = "Nuevo Paciente";

            if (ID != 0)
            {
                ViewBag.Accion = "Editar Paciente";
                modelo_paciente = await _serviceApi.ObtenerPaciente(ID);
            }
            return View(modelo_paciente);
        }
        [HttpPost]
        public async Task<ActionResult> GuardarPaciente(Paciente obj_paciente)
        {
            bool respuesta;

            Console.WriteLine("Se reconoció que el ID es distinto a 0.");
            respuesta = await _serviceApi.UpdatePaciente(obj_paciente);

            if (respuesta)
            {
                Console.WriteLine("Funcionó Correctamente.");
                return RedirectToAction("ListarPacientes");
            }
            else
            {
                Console.WriteLine("No funcionó :/.");
                return NoContent();
            }
        }
        public async Task<ActionResult> Detallepaciente(int ID)
        {
            Paciente modelo_paciente = new Paciente();/*Se debe traer al modelo correspondiente*/

            ViewBag.Accion = "Nuevo Paciente";

            if (ID != 0)
            {
                ViewBag.Accion = "Editar Paciente";
                modelo_paciente = await _serviceApi.ObtenerPaciente(ID);
            }
            return View(modelo_paciente);
        }
        public IActionResult Editarpaciente()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PruebaController.cs
using CCVLab.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CCVLab.Controllers
{
    public class PruebaController : Controller
    {
        private readonly ILogger<PruebaController> _logger;

        public PruebaController(ILogger<PruebaController> logger)
        {
            _logger = logger;
        }

        public IActionResult Prueba()
        {
            return View();
        }

        public IActionResult Detallepaciente()
        {
            return View();
        }
        public IActionResult Editarpaciente()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CCVLab</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Menu.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CCVLab.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <script src="https://kit.fontawesome.com/019078dbc4.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar-principal">
            <div class="franja-azul">
                <div class="menu-desplegable">
                    <label for="btn-menu-desplegable" class="fa-solid fa-bars"></label>
                </div>
                <div class="logo">
                    <img src="~/image/logo.png" alt="Logo" />
                </div>
                <a class="profile-button" href="#">
                    Profile 
                    <label class="icon-profile">
                        <FontAwesomeIcon icon={faCircleUser} />
                    </label>
                </a>
            </div>
        </nav>
    </header>
    <input type="checkbox" id="btn-menu-desplegable">
    <div class="container-menu-desplegable">
        <div class="contenido-menu-desplegable">
            <nav>
                <a asp-area="" asp-controller="Paciente" asp-action="ListarPacientes">Pacientes</a>                
                <a asp-area="" asp-controller="Paciente" asp-action="Crearpaciente">Crear Paciente</a>
                <a asp-area="" asp-controller="Paciente" asp-action="Detallepaciente">Detalle Paciente</a>
                <a asp-area="" asp-controller="Paciente" asp-action="Editarpaciente">Editar Paciente</a>
                <a asp-area="" asp-controller="Prueba" asp-action="Prueba">Pruebas</a>
                <a asp-area="" asp-controller="Citas" asp-action="ListarCitas">Citas</a>
                <a asp-area="" asp-controller="Citas" asp-action="CrearCitas">Crear Citas</a>
                <a asp-area="" asp-controller="Citas" asp-action="EditarCitas">Editar Citas</a>
                <a asp-area="" asp-controller="Citas" asp-action="DetalleCitas">Detalle de Citas</a>
                <a asp-area="" asp-controller="Login" asp-action="Logout">Cerrar Sesión</a>
            </nav>
            <label for="btn-menu-desplegable" class="fa-solid fa-xmark"></label>
        </div>
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>