Controllers/CitasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using CCVLab.Models;
using System.Security.Claims;
using CCVLab.Data;
using CCVLab.Services;

namespace CCVLab.Controllers
{
    public class CitasController : Controller
    {
        private readonly IService_API _serviceApi;
        private readonly IService_API_Paciente _serviceApiPaciente;
        private readonly IService_API_Examen _serviceApiExamen;

        public CitasController(IService_API service_API, IService_API_Paciente service_API_Paciente, IService_API_Examen service_API_Examen)
        {
            _serviceApi = service_API;
            _serviceApiPaciente = service_API_Paciente;
            _serviceApiExamen = service_API_Examen;
        }
        public async Task<ActionResult> ListarCitas()
        {
            List<ViewCita> lista = await _serviceApi.Lista();
            return View(lista);
        }
        public async Task<ActionResult> CrearCitas()
        {
            var listaPacientes = await _serviceApiPaciente.Lista();
            var listaExamenes = await _serviceApiExamen.Lista();

            ViewBag.ListaPacientes = listaPacientes;
            ViewBag.listaExamenes = listaExamenes;

            return View();
        }
        public async Task<ActionResult> Cita(int ID)
        {
            Cita modelo_cita = new Cita();

            ViewBag.Accion = "Nueva Cita";

            if (ID != 0)
            {
                modelo_cita = await _serviceApi.ObtenerCita(ID);
                ViewBag.Accion = "Editar Cita";
            }
            return View(modelo_cita);
        }

        public async Task<ActionResult> DetalleCitas(int ID)
        {
            Cita modelo_cita = new Cita();/*Se debe traer al modelo correspondiente*/

            ViewBag.Accion = "Nueva Cita";

            if (ID != 0)
            {
                modelo_cita = await _serviceApi.ObtenerCita(ID);
                ViewBag.Accion = "Detalle de la Cita";
            }
            return View(modelo_cita);
        }

        [HttpPost]
        public async Task<ActionResult> GuardarCita(CreateCitaModel obj_cita)
        {
            bool respuesta;

            if (obj_cita.ID == 0)
            {
                var examenesSeleccionadosValues = Request.Form["Examenes"];
                if (examenesSeleccionadosValues.Count > 0)
                {
                    obj_cita.Examenes = examenesSeleccionadosValues.Select(int.Parse).ToList();
                }

                respuesta = await _serviceApi.CreateCita(obj_cita);
            }
            else
            {
                respuesta = await _serviceApi.UpdateCita(obj_cita);
            }

            if (respuesta)
                return RedirectToAction("ListarCitas");
            else
                return NoContent();
        }
    }
}

Views/Citas/Cita.cshtml
@model Cita
@{
    ViewData["Title"] = "Crear citas";
}
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Crear citas</title>
    <link rel="stylesheet" href="~/css/CrearCitas.css" />
</head>

<body>
    <h1 class='tittle-text'>@ViewBag.Accion</h1>
    <form asp-action="GuardarCita" asp-controller="Citas" method="post">
        <input type="hidden" asp-for="ID" />
        <div class='box-crear-formulario'>
            <h3 class="Subtittle">Datos del Cliente</h3>
            <div class='box-data-user'>
                <div class='box-data-user-column1'>
                    <div class="file">
                        <label class="Texto-input">Tipo de documento</label>
                        <select class="input-form" id="estado" name="estado" />
                            <option value="1">DNI</option>
                            <option value="2">Carné de Extranjería</option>
                        </select>
                    </div>
                    <div class="file">
                        <label class="Texto-input">Nro. de documento</label>
                        <div class="input-container">
                            <input id="dni" name="dni" type="number" class="input-form" asp-action="DNI_Paciente"/>
                            <button id="boton" class="btn-validar">Validar</button>
                        </div>
                    </div>
                    <div class="file">
                        <label class="Texto-input">Nombres</label>
                        <input readonly="" id="nombre" type="text" class="input-form" />
                    </div>
                    <div class="file">
                        <label class="Texto-input">Apellidos</label>
                        <input readonly="" id="apellido" type="text" class="input-form" />
                    </div>
                </div>
                <div class='box-data-user-column2'>
                    <div class="file">
                        <label class="Texto-input">Fecha de nacimiento</label>
                        <input type="date" class="input-form" id="fecha" name="fecha" />
                    </div>
                    <div class="file">
                        <label class="Texto-input">Email</label>
                        <input type="text" class="input-form" />
                    </div>
                    <div class="file">
                        <label class="Texto-input">Dirección</label>
                        <input type="text" class="input-form" />
                    </div>
                    <div class="file">
                        <label class="Texto-input">Encargado actual:</label>
                        <select class="input-form" name="prueba" asp-for="FK_Usuario">
                            <option value="1">Carlos Gonzales</option>
                        </select>
                    </div>
                </div>
            </div>
            <h3 class="Subtittle">Detalles de la cita</h3>
            <div class='box-data-cita'>
                <div class='box-data-cita-column1'>
                    <div class="file">
                        <label class="Texto-input">Fecha</label>
                        <input type="date" class="input-form" name="fecha" />
                    </div>
                    <div class="file">
                        <label class="Texto-input">Estado</label>
                        <select class="input-form" id="estado" name="estado">
                            <option value="1">En espera</option>
                            <option value="2">En proceso</option>
                            <option value="3">En revisión</option>
                            <option value="4">Finalizado</option>
                            <option value="5">Cancelado</option>
                            <option value="6">Suspendido</option>
                        </select>
                    </div>
                    <div class="file">
                        <label class="Texto-input">Prueba</label>
                        <select class="input-form" name="prueba">
                            <option value="1">Hemograma completo</option>
                            <option value="2">Perfil Lipídico</option>
                            <option value="3">Glucosa</option>
                            <option value="4">Prueba de embarazo</option>
                        </select>
                    </div>
                </div>
                <div class='box-data-cita-column2'>
                    <div class="file">
                        <label class="Texto-input">Hora</label>
                        <input type="time" class="input-form" id="hora" name="hora" />
                    </div>
                    <div class="file">
                        <label class="Texto-input">Sucursal</label>
                        <select class="input-form" id="sucursal" name="sucursal">
                            <option value="1">Lima</option>
                            <option value="2">Arequipa</option>
                            <option value="3">Ica</option>
                        </select>
                    </div>
                    <div class="file">
                        <label class="Texto-input">Total</label>
                        <input type="text" class="input-form" />
                    </div>
                    <div class="file">
                        <label class="Texto-input">Estado de Pago</label>
                        <select class="input-form" id="sucursal" name="sucursal">
                            <option value="1">Falta Pagar</option>
                            <option value="2">Medio Pago</option>
                            <option value="3">Pagado</option>
                        </select>
                    </div>
                    <div class="file">
                        <label class="Texto-input">Observación</label>
                        <textarea id="miTextArea" name="miTextArea" rows="4" cols="50">Ninguna</textarea>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn-formulario">Guardar Cambios</button>
            <a asp-action="ListarCitas" asp-controller="Citas" class="btn btn-warning btn-sm">Volver a lista</a>
        </div>
    </form>
    <script src="~/js/Main.js" asp-append-version="true"></script>
</body>

</html>

Views/Citas/CrearCitas.cshtml
@model CreateCitaModel
@{
    ViewData["Title"] = "Crear citas";
}
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Crear citas</title>
    <link rel="stylesheet" href="~/css/CrearCitas.css" />
</head>

<body>
    <h1 class='tittle-text'>Crear Citas</h1>
    <form asp-action="GuardarCita" asp-controller="Citas" method="post">
        <div class='box-crear-formulario'>
            <h3 class="Subtittle">Datos del Cliente</h3>
            <div class='box-data-user'>
                <div class='box-data-user-column1'>
                    <div class="file">
                        <label class="Texto-input">Tipo de documento</label>
                        <input readonly="" id="Tipo_Documento" type="text" class="input-form" />
                    </div>
                    <div class="file">
                        <label class="Texto-input">Nombres</label>
                        <input readonly="" id="nombres" type="text" class="input-form" />
                    </div>

                </div>
                <div class='box-data-user-column2'>
                    <div class="file">
                        <label class="Texto-input">Nro. de documento</label>
                        <div class="input-container">
                            <input type="text" id="searchInput" placeholder="Buscar DNI" oninput="filterOptions()">
                            <select id="selectDocumento" class="input-form" asp-for="FK_Paciente">
                                <option value="">Seleccione un número de Doc.</option>
                                @foreach (var paciente in ViewBag.ListaPacientes)
                                {
                                    <option value="@paciente.ID" data-tipo-documento="@paciente.Tipo_Documento"
                                        data-nombres="@paciente.Nombres" data-apellidos="@paciente.Apellidos">
                                        @paciente.Nro_DNI
                                    </option>
                                }
                            </select>
                            <button id="boton" class="btn-validar">Validar</button>
                        </div>
                    </div>

                    <script>
                        function filterOptions() {
                        var input, filter, select, options, option, i, txtValue;
                        input = document.getElementById("searchInput");
                        filter = input.value.toUpperCase();
                        select = document.getElementById("selectDocumento");
                        options = select.getElementsByTagName("option");

                        for (i = 0; i < options.length; i++) {
                            option = options[i];
                            txtValue = option.textContent || option.innerText;
                            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                                option.style.display = "";
                            } else {
                                option.style.display = "none";
                            }
                        }
                    }

                        // Función para actualizar los campos con los datos del paciente seleccionado
                        function actualizarDatosPaciente() {
                            var selectDocumento = document.getElementById("selectDocumento");
                            var Tipo_Documento = document.getElementById("Tipo_Documento");
                            var nombres = document.getElementById("nombres");
                            var apellidos = document.getElementById("apellido");

                            // Obtener el índice del elemento seleccionado
                            var selectedIndex = selectDocumento.selectedIndex;

                            // Verificar si se ha seleccionado un paciente
                            if (selectedIndex !== -1) {
                                // Obtener los atributos personalizados del elemento seleccionado
                                Tipo_Documento.value = selectDocumento.options[selectedIndex].getAttribute("data-tipo-documento");
                                nombres.value = selectDocumento.options[selectedIndex].getAttribute("data-nombres");
                                apellidos.value = selectDocumento.options[selectedIndex].getAttribute("data-apellidos");
                            } else {
                                // Limpiar campos si no hay paciente seleccionado
                                Tipo_Documento.value = "";
                                nombres.value = "";
                                apellidos.value = "";
                            }
                        }

                        // Agregar manejadores de eventos
                        var selectDocumento = document.getElementById("selectDocumento");
                        selectDocumento.addEventListener('change', function () {
                            // Actualizar datos del paciente cuando se selecciona un documento
                            actualizarDatosPaciente();
                        });
                    </script>

                    <div class="file">
                        <label class="Texto-input">Apellidos</label>
                        <input readonly="" id="apellido" type="text" class="input-form" />
                    </div>

                </div>
            </div>
            <h3 class="Subtittle">Detalles de la cita</h3>
            <div class='box-data-cita'>
                <div class='box-data-cita-column1'>
                    <div class="file">
                        <label class="Texto-input">Fecha</label>
                        <input type="date" class="input-form" id="fecha" name="fecha" asp-for="Fecha" />
                    </div>
                    <div class="file">
                        <label class="Texto-input">Estado</label>
                        <select class="input-form" id="estado" name="FK_Estado" asp-for="FK_Estado">
                            <option value="1">En espera</option>
                            <option value="2">En proceso</option>
                            <option value="3">En revisión</option>
                            <option value="4">Finalizado</option>
                            <option value="5">Cancelado</option>
                            <option value="6">Suspendido</option>
                        </select>
                    </div>

                    <div class="file">
                        <label class="Texto-input">Exámenes Médicos</label>
                        <table>
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Nombre del Examen</th>
                                    <th>Precio</th>
                                    <th>Seleccionar</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var examen in ViewBag.listaExamenes)
                                {
                                    <tr>
                                        <td>@examen.ID</td>
                                        <td>@examen.Nombre</td>
                                        <td>@examen.Precio</td>
                                        <td>
                                            <input type="checkbox" class="checkboxExamen" data-precio="@examen.Precio"
                                                name="Examenes" value="@examen.ID" />
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>

                    <div class="file">
                        <label class="Texto-input">Total Unitario</label>
                        <input type="text" class="input-form" id="totalUnitario" readonly />
                    </div>

                    <script>
                        // Función para calcular y actualizar el Total Unitario, IGV y Monto Total
                        function actualizarTotales() {
                            var totalUnitario = 0;
                            // Obtener todos los checkboxes seleccionados
                            var checkboxes = document.querySelectorAll('.checkboxExamen:checked');
                            checkboxes.forEach(function (checkbox) {
                                // Sumar el precio de los exámenes seleccionados
                                totalUnitario += parseFloat(checkbox.getAttribute('data-precio'));
                            });

                            // Calcular IGV (18%)
                            var igv = totalUnitario * 0.18;

                            // Calcular Monto Total sumando el IGV al Total Unitario
                            var montoTotal = totalUnitario + igv;

                            // Actualizar los campos
                            document.getElementById('totalUnitario').value = totalUnitario.toFixed(2);
                            document.getElementById('igv').value = igv.toFixed(2);
                            document.getElementById('montoTotal').value = montoTotal.toFixed(2);
                        }

                        // Agregar manejadores de eventos a los checkboxes
                        var checkboxes = document.querySelectorAll('.checkboxExamen');
                        checkboxes.forEach(function (checkbox) {
                            checkbox.addEventListener('change', function () {
                                actualizarTotales();
                            });
                        });
                    </script>

                </div>
                <div class='box-data-cita-column2'>
                    <div class="file">
                        <label class="Texto-input">Hora</label>
                        <input type="time" class="input-form" id="hora" name="hora" asp-for="Hora" />
                    </div>
                    <div class="file">
                        <label class="Texto-input">Referencia:</label>
                        <select class="input-form" id="sucursal" name="FK_Sucursal" asp-for="FK_Sucursal">
                            <option value="1">Lima</option>
                            <option value="2">Arequipa</option>
                            <option value="3">Ica</option>
                        </select>
                    </div>
                    <div class="file">
                        <label class="Texto-input">Urgencia</label>
                        <select class="input-form" id="urgencia" name="FK_Urgencia" asp-for="FK_Urgencia">
                            <option value="2">No</option>
                            <option value="1">Si</option>
                            <option value="3">Prioridad</option>
                        </select>
                    </div>
                    <div class="file">
                        <label class="Texto-input">Encargado actual:</label>
                        <select class="input-form" id="FK_Usuario" name="FK_Usuario" asp-for="FK_Usuario">
                            <option value="1">Carlos Gonzales</option>
                        </select>
                    </div>
                    <div class="file">
                        <label class="Texto-input">Estado de Pago</label>
                        <select class="input-form" id="sucursal" name="FK_Estado_Pago" asp-for="FK_Estado_Pago">
                            <option value="1">Falta Pagar</option>
                            <option value="2">Medio Pago</option>
                            <option value="3">Pagado</option>
                        </select>
                    </div>
                    <div class="file">
                        <label class="Texto-input">Observación</label>
                        <textarea id="Observacion" name="Observacion" rows="4" cols="50"
                            asp-for="Observacion">Ninguna</textarea>
                    </div>
                    <div class="file">
                        <label class="Texto-input">IGV (18%)</label>
                        <input type="text" class="input-form" id="igv" readonly />
                    </div>
                    <div class="file">
                        <label class="Texto-input">Total a pagar</label>
                        <input type="text" class="input-form" id="montoTotal" readonly />
                    </div>
                </div>
            </div>
            <button type="submit" class="btn-formulario">Registrar Cita</button>
        </div>
    </form>
    <script src="~/js/Main.js" asp-append-version="true"></script>
</body>

</html>

Views/Citas/DetalleCitas.cshtml
@model CCVLab.Models.Cita
@{
    ViewData["Title"] = "Editar citas";
}
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Editar citas</title>
        <link rel="stylesheet" href="~/css/CrearCitas.css" />
    </head>
    <body>
        <h1 class='tittle-text'>Detalle de la Cita</h1>
    <div class='box-crear-formulario'>
        <h3 class="Subtittle">Datos del Cliente</h3>
        <div class='box-data-user'>
            <div class='box-data-user-column1'>
                <div class="file">
                    <label class="Texto-input">Tipo de documento</label>
                    <input id="dni" name="dni" type="text" class="input-form" asp-for="Tipo_Documento" disabled />
                </div>
                <div class="file">
                    <label class="Texto-input">Nro. de documento</label>
                    <input id="dni" name="dni" type="number" class="input-form" disabled asp-for="DNI_Paciente"/>
                </div>
                
            </div>
            <div class='box-data-user-column2'>
                <div class="file">
                    <label class="Texto-input">Nombres</label>
                    <input readonly="" id="nombre" type="text" class="input-form" disabled asp-for="Nombres_Paciente"/>
                </div>
                <div class="file">
                    <label class="Texto-input">Apellidos</label>
                    <input readonly="" id="apellido" type="text" class="input-form" disabled asp-for="Apellidos_Paciente"/>
                </div>
                
            </div>
        </div>
        <h3 class="Subtittle">Detalles de la cita</h3>
        <div class='box-data-cita'>
            <div class='box-data-cita-column1'>
                <div class="file">
                    <label class="Texto-input">Fecha</label>
                    <input type="date" class="input-form" id="fecha" name="fecha" disabled asp-for="Fecha"/>
                </div>
                <div class="file">
                    <label class="Texto-input">Estado</label>
                    <input type="text" class="input-form" id="fecha" name="fecha" disabled asp-for="FK_Estado"/>
                </div>
                <div class="file">
                    <label class="Texto-input">Prueba</label>
                    <select class="input-form" id="prueba" name="prueba" disabled >
                        <option value="hc">Hemograma completo</option>
                        <option value="pl">Perfil Lipídico</option>
                        <option value="g">Glucosa</option>
                        <option value="pe">Prueba de embarazo</option>
                    </select>
                </div>
            </div>
            <div class='box-data-cita-column2'>
                <div class="file">
                    <label class="Texto-input">Hora</label>
                    <input type="time" class="input-form" id="hora" name="hora" disabled asp-for="Hora"/>
                </div>
                <div class="file">
                    <label class="Texto-input">Sucursal</label>
                    <input type="text" class="input-form" id="fecha" name="fecha" disabled asp-for="FK_Sucursal"/>
                </div>
                <div class="file">
                    <label class="Texto-input">Total</label>
                    <input type="text" class="input-form" disabled/>
                </div>
            </div>
        </div>
    </div>
    </body>
</html>

Views/Citas/ListarCitas.cshtml
@model List<ViewCita>
@{
    ViewData["Title"] = "Listar Citas";
}
<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Pruebas</title>
    <link rel="stylesheet" href="~/css/Listarpaciente.css" />
    <link rel="stylesheet" href="~/css/General.css" />
</head>

<body>
    <h1 class='tittle-text'>Citas Registradas</h1>
    <!-- Contenedor para alinear el buscador y el botón a los extremos -->
    <div class="header-container">
        <!-- Buscador -->
        <div class="search-container">
            <p>Buscar:</p>
            <input type="text" id="searchInput" placeholder="Ingrese el DNI del afiliado">
            <button onclick="searchTable()">Buscar</button>
        </div>

        <!-- Botón "Crear Cita" -->
        <a asp-action="CrearCitas" asp-controller="Citas" asp-route-ID="0" class="crear-prueba-btn">Crear Cita</a>
    </div>
    <div class="wrap-table100">
        <div class="table100">
            <table>
                <thead>
                    <tr class="table100-head">
                        <th class="column1">ID</th>
                        <th class="column4">DNI</th>
                        <th class="column5">Fecha</th>
                        <th class="column4">Urgencia</th>
                        <th class="column5">Estado</th>
                        <th class="column5">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="column1">@item.ID</td>
                            <td class="column4">@item.DNI_Paciente</td>
                            <td class="column5">@item.Fecha</td>
                            <td class="column4">@item.FK_Urgencia</td>
                            <td class="column5">@item.FK_Estado</td>
                            <td class="column5">
                                <div class="acciones-btns">
                                    <a asp-action="DetalleCitas" asp-controller="Citas" asp-route-ID="@item.ID" class="visualizar-btn">Ver</a>
                                    <a asp-action="Cita" asp-controller="Citas" asp-route-ID="@item.ID" class="editar-btn">Editar</a>
                                    <button class="eliminar-btn">Eliminar</button>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>

</html>